export interface Element {
  symbol: string;
  name: string;
  atomicNumber: number;
  atomicMass: number;
}

// Complete periodic table - all 118 elements
// Masses use IUPAC 2021 standard atomic weights
// Elements without stable isotopes use mass of longest-lived isotope
export const PERIODIC_TABLE: Record<string, Element> = {
  // Period 1
  'H':  { symbol: 'H',  name: 'Hydrogen',      atomicNumber: 1,   atomicMass: 1.008 },
  'He': { symbol: 'He', name: 'Helium',         atomicNumber: 2,   atomicMass: 4.003 },
  // Period 2
  'Li': { symbol: 'Li', name: 'Lithium',        atomicNumber: 3,   atomicMass: 6.941 },
  'Be': { symbol: 'Be', name: 'Beryllium',      atomicNumber: 4,   atomicMass: 9.012 },
  'B':  { symbol: 'B',  name: 'Boron',          atomicNumber: 5,   atomicMass: 10.81 },
  'C':  { symbol: 'C',  name: 'Carbon',         atomicNumber: 6,   atomicMass: 12.011 },
  'N':  { symbol: 'N',  name: 'Nitrogen',       atomicNumber: 7,   atomicMass: 14.007 },
  'O':  { symbol: 'O',  name: 'Oxygen',         atomicNumber: 8,   atomicMass: 15.999 },
  'F':  { symbol: 'F',  name: 'Fluorine',       atomicNumber: 9,   atomicMass: 18.998 },
  'Ne': { symbol: 'Ne', name: 'Neon',           atomicNumber: 10,  atomicMass: 20.180 },
  // Period 3
  'Na': { symbol: 'Na', name: 'Sodium',         atomicNumber: 11,  atomicMass: 22.990 },
  'Mg': { symbol: 'Mg', name: 'Magnesium',      atomicNumber: 12,  atomicMass: 24.305 },
  'Al': { symbol: 'Al', name: 'Aluminium',      atomicNumber: 13,  atomicMass: 26.982 },
  'Si': { symbol: 'Si', name: 'Silicon',        atomicNumber: 14,  atomicMass: 28.085 },
  'P':  { symbol: 'P',  name: 'Phosphorus',     atomicNumber: 15,  atomicMass: 30.974 },
  'S':  { symbol: 'S',  name: 'Sulfur',         atomicNumber: 16,  atomicMass: 32.06 },
  'Cl': { symbol: 'Cl', name: 'Chlorine',       atomicNumber: 17,  atomicMass: 35.45 },
  'Ar': { symbol: 'Ar', name: 'Argon',          atomicNumber: 18,  atomicMass: 39.948 },
  // Period 4
  'K':  { symbol: 'K',  name: 'Potassium',      atomicNumber: 19,  atomicMass: 39.098 },
  'Ca': { symbol: 'Ca', name: 'Calcium',        atomicNumber: 20,  atomicMass: 40.078 },
  'Sc': { symbol: 'Sc', name: 'Scandium',       atomicNumber: 21,  atomicMass: 44.956 },
  'Ti': { symbol: 'Ti', name: 'Titanium',       atomicNumber: 22,  atomicMass: 47.867 },
  'V':  { symbol: 'V',  name: 'Vanadium',       atomicNumber: 23,  atomicMass: 50.942 },
  'Cr': { symbol: 'Cr', name: 'Chromium',       atomicNumber: 24,  atomicMass: 51.996 },
  'Mn': { symbol: 'Mn', name: 'Manganese',      atomicNumber: 25,  atomicMass: 54.938 },
  'Fe': { symbol: 'Fe', name: 'Iron',           atomicNumber: 26,  atomicMass: 55.845 },
  'Co': { symbol: 'Co', name: 'Cobalt',         atomicNumber: 27,  atomicMass: 58.933 },
  'Ni': { symbol: 'Ni', name: 'Nickel',         atomicNumber: 28,  atomicMass: 58.693 },
  'Cu': { symbol: 'Cu', name: 'Copper',         atomicNumber: 29,  atomicMass: 63.546 },
  'Zn': { symbol: 'Zn', name: 'Zinc',           atomicNumber: 30,  atomicMass: 65.38 },
  'Ga': { symbol: 'Ga', name: 'Gallium',        atomicNumber: 31,  atomicMass: 69.723 },
  'Ge': { symbol: 'Ge', name: 'Germanium',      atomicNumber: 32,  atomicMass: 72.630 },
  'As': { symbol: 'As', name: 'Arsenic',        atomicNumber: 33,  atomicMass: 74.922 },
  'Se': { symbol: 'Se', name: 'Selenium',       atomicNumber: 34,  atomicMass: 78.971 },
  'Br': { symbol: 'Br', name: 'Bromine',        atomicNumber: 35,  atomicMass: 79.904 },
  'Kr': { symbol: 'Kr', name: 'Krypton',        atomicNumber: 36,  atomicMass: 83.798 },
  // Period 5
  'Rb': { symbol: 'Rb', name: 'Rubidium',       atomicNumber: 37,  atomicMass: 85.468 },
  'Sr': { symbol: 'Sr', name: 'Strontium',      atomicNumber: 38,  atomicMass: 87.62 },
  'Y':  { symbol: 'Y',  name: 'Yttrium',        atomicNumber: 39,  atomicMass: 88.906 },
  'Zr': { symbol: 'Zr', name: 'Zirconium',      atomicNumber: 40,  atomicMass: 91.224 },
  'Nb': { symbol: 'Nb', name: 'Niobium',        atomicNumber: 41,  atomicMass: 92.906 },
  'Mo': { symbol: 'Mo', name: 'Molybdenum',     atomicNumber: 42,  atomicMass: 95.95 },
  'Tc': { symbol: 'Tc', name: 'Technetium',     atomicNumber: 43,  atomicMass: 98 },
  'Ru': { symbol: 'Ru', name: 'Ruthenium',      atomicNumber: 44,  atomicMass: 101.07 },
  'Rh': { symbol: 'Rh', name: 'Rhodium',        atomicNumber: 45,  atomicMass: 102.906 },
  'Pd': { symbol: 'Pd', name: 'Palladium',      atomicNumber: 46,  atomicMass: 106.42 },
  'Ag': { symbol: 'Ag', name: 'Silver',         atomicNumber: 47,  atomicMass: 107.868 },
  'Cd': { symbol: 'Cd', name: 'Cadmium',        atomicNumber: 48,  atomicMass: 112.414 },
  'In': { symbol: 'In', name: 'Indium',         atomicNumber: 49,  atomicMass: 114.818 },
  'Sn': { symbol: 'Sn', name: 'Tin',            atomicNumber: 50,  atomicMass: 118.710 },
  'Sb': { symbol: 'Sb', name: 'Antimony',       atomicNumber: 51,  atomicMass: 121.760 },
  'Te': { symbol: 'Te', name: 'Tellurium',      atomicNumber: 52,  atomicMass: 127.60 },
  'I':  { symbol: 'I',  name: 'Iodine',         atomicNumber: 53,  atomicMass: 126.904 },
  'Xe': { symbol: 'Xe', name: 'Xenon',          atomicNumber: 54,  atomicMass: 131.293 },
  // Period 6
  'Cs': { symbol: 'Cs', name: 'Caesium',        atomicNumber: 55,  atomicMass: 132.905 },
  'Ba': { symbol: 'Ba', name: 'Barium',         atomicNumber: 56,  atomicMass: 137.327 },
  'La': { symbol: 'La', name: 'Lanthanum',      atomicNumber: 57,  atomicMass: 138.905 },
  'Ce': { symbol: 'Ce', name: 'Cerium',         atomicNumber: 58,  atomicMass: 140.116 },
  'Pr': { symbol: 'Pr', name: 'Praseodymium',   atomicNumber: 59,  atomicMass: 140.908 },
  'Nd': { symbol: 'Nd', name: 'Neodymium',      atomicNumber: 60,  atomicMass: 144.242 },
  'Pm': { symbol: 'Pm', name: 'Promethium',     atomicNumber: 61,  atomicMass: 145 },
  'Sm': { symbol: 'Sm', name: 'Samarium',       atomicNumber: 62,  atomicMass: 150.36 },
  'Eu': { symbol: 'Eu', name: 'Europium',       atomicNumber: 63,  atomicMass: 151.964 },
  'Gd': { symbol: 'Gd', name: 'Gadolinium',     atomicNumber: 64,  atomicMass: 157.25 },
  'Tb': { symbol: 'Tb', name: 'Terbium',        atomicNumber: 65,  atomicMass: 158.925 },
  'Dy': { symbol: 'Dy', name: 'Dysprosium',     atomicNumber: 66,  atomicMass: 162.500 },
  'Ho': { symbol: 'Ho', name: 'Holmium',        atomicNumber: 67,  atomicMass: 164.930 },
  'Er': { symbol: 'Er', name: 'Erbium',         atomicNumber: 68,  atomicMass: 167.259 },
  'Tm': { symbol: 'Tm', name: 'Thulium',        atomicNumber: 69,  atomicMass: 168.934 },
  'Yb': { symbol: 'Yb', name: 'Ytterbium',      atomicNumber: 70,  atomicMass: 173.045 },
  'Lu': { symbol: 'Lu', name: 'Lutetium',       atomicNumber: 71,  atomicMass: 174.967 },
  'Hf': { symbol: 'Hf', name: 'Hafnium',       atomicNumber: 72,  atomicMass: 178.49 },
  'Ta': { symbol: 'Ta', name: 'Tantalum',       atomicNumber: 73,  atomicMass: 180.948 },
  'W':  { symbol: 'W',  name: 'Tungsten',       atomicNumber: 74,  atomicMass: 183.84 },
  'Re': { symbol: 'Re', name: 'Rhenium',        atomicNumber: 75,  atomicMass: 186.207 },
  'Os': { symbol: 'Os', name: 'Osmium',         atomicNumber: 76,  atomicMass: 190.23 },
  'Ir': { symbol: 'Ir', name: 'Iridium',        atomicNumber: 77,  atomicMass: 192.217 },
  'Pt': { symbol: 'Pt', name: 'Platinum',       atomicNumber: 78,  atomicMass: 195.084 },
  'Au': { symbol: 'Au', name: 'Gold',           atomicNumber: 79,  atomicMass: 196.967 },
  'Hg': { symbol: 'Hg', name: 'Mercury',        atomicNumber: 80,  atomicMass: 200.592 },
  'Tl': { symbol: 'Tl', name: 'Thallium',       atomicNumber: 81,  atomicMass: 204.38 },
  'Pb': { symbol: 'Pb', name: 'Lead',           atomicNumber: 82,  atomicMass: 207.2 },
  'Bi': { symbol: 'Bi', name: 'Bismuth',        atomicNumber: 83,  atomicMass: 208.980 },
  'Po': { symbol: 'Po', name: 'Polonium',       atomicNumber: 84,  atomicMass: 209 },
  'At': { symbol: 'At', name: 'Astatine',       atomicNumber: 85,  atomicMass: 210 },
  'Rn': { symbol: 'Rn', name: 'Radon',          atomicNumber: 86,  atomicMass: 222 },
  // Period 7
  'Fr': { symbol: 'Fr', name: 'Francium',       atomicNumber: 87,  atomicMass: 223 },
  'Ra': { symbol: 'Ra', name: 'Radium',         atomicNumber: 88,  atomicMass: 226 },
  'Ac': { symbol: 'Ac', name: 'Actinium',       atomicNumber: 89,  atomicMass: 227 },
  'Th': { symbol: 'Th', name: 'Thorium',        atomicNumber: 90,  atomicMass: 232.038 },
  'Pa': { symbol: 'Pa', name: 'Protactinium',   atomicNumber: 91,  atomicMass: 231.036 },
  'U':  { symbol: 'U',  name: 'Uranium',        atomicNumber: 92,  atomicMass: 238.029 },
  'Np': { symbol: 'Np', name: 'Neptunium',      atomicNumber: 93,  atomicMass: 237 },
  'Pu': { symbol: 'Pu', name: 'Plutonium',      atomicNumber: 94,  atomicMass: 244 },
  'Am': { symbol: 'Am', name: 'Americium',      atomicNumber: 95,  atomicMass: 243 },
  'Cm': { symbol: 'Cm', name: 'Curium',         atomicNumber: 96,  atomicMass: 247 },
  'Bk': { symbol: 'Bk', name: 'Berkelium',      atomicNumber: 97,  atomicMass: 247 },
  'Cf': { symbol: 'Cf', name: 'Californium',    atomicNumber: 98,  atomicMass: 251 },
  'Es': { symbol: 'Es', name: 'Einsteinium',    atomicNumber: 99,  atomicMass: 252 },
  'Fm': { symbol: 'Fm', name: 'Fermium',        atomicNumber: 100, atomicMass: 257 },
  'Md': { symbol: 'Md', name: 'Mendelevium',    atomicNumber: 101, atomicMass: 258 },
  'No': { symbol: 'No', name: 'Nobelium',       atomicNumber: 102, atomicMass: 259 },
  'Lr': { symbol: 'Lr', name: 'Lawrencium',     atomicNumber: 103, atomicMass: 266 },
  'Rf': { symbol: 'Rf', name: 'Rutherfordium',  atomicNumber: 104, atomicMass: 267 },
  'Db': { symbol: 'Db', name: 'Dubnium',        atomicNumber: 105, atomicMass: 268 },
  'Sg': { symbol: 'Sg', name: 'Seaborgium',     atomicNumber: 106, atomicMass: 269 },
  'Bh': { symbol: 'Bh', name: 'Bohrium',        atomicNumber: 107, atomicMass: 270 },
  'Hs': { symbol: 'Hs', name: 'Hassium',        atomicNumber: 108, atomicMass: 277 },
  'Mt': { symbol: 'Mt', name: 'Meitnerium',     atomicNumber: 109, atomicMass: 278 },
  'Ds': { symbol: 'Ds', name: 'Darmstadtium',   atomicNumber: 110, atomicMass: 281 },
  'Rg': { symbol: 'Rg', name: 'Roentgenium',    atomicNumber: 111, atomicMass: 282 },
  'Cn': { symbol: 'Cn', name: 'Copernicium',    atomicNumber: 112, atomicMass: 285 },
  'Nh': { symbol: 'Nh', name: 'Nihonium',       atomicNumber: 113, atomicMass: 286 },
  'Fl': { symbol: 'Fl', name: 'Flerovium',      atomicNumber: 114, atomicMass: 289 },
  'Mc': { symbol: 'Mc', name: 'Moscovium',      atomicNumber: 115, atomicMass: 290 },
  'Lv': { symbol: 'Lv', name: 'Livermorium',    atomicNumber: 116, atomicMass: 293 },
  'Ts': { symbol: 'Ts', name: 'Tennessine',     atomicNumber: 117, atomicMass: 294 },
  'Og': { symbol: 'Og', name: 'Oganesson',      atomicNumber: 118, atomicMass: 294 },
};

// Convenience: mass-only lookup (backward compatible)
export const ELEMENT_MASSES: Record<string, number> = Object.fromEntries(
  Object.entries(PERIODIC_TABLE).map(([sym, el]) => [sym, el.atomicMass])
);
